version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.12
  build:
    commands:
      - aws cloudformation package --template-file python/upload-to-search.yaml --s3-bucket searchproject-codebuild --output-template-file python/upload-to-search-output.yaml
      #Package cloudFormation template and output to the same path that CodePipeline expects
artifacts:
  type: zip
  files:
    - python/upload-to-search-output.yaml
    - python/lambda_function.py

